name: grandtouryt
description: Youtube API test project
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  logger: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  
  # Google API
  google_sign_in: ^5.4.2
  googleapis: ^9.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.7

  # UI
  lottie: ^1.4.3
  infinite_scroll_pagination: ^3.2.0
  youtube_player_flutter: ^8.1.0
  google_fonts: ^3.0.1
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  flutter_gen_runner: ^5.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/white_noise.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter